### ISSUE TITLE
Around the time I upgraded from Nuxt 3.1.2 to 3.3.0, animations using the vue3-lottie library are not working.

### ISSUE THREAD

**Issue by boeltazawa** [megasanjay/vue3-lottie#314]
Around the time I upgraded from Nuxt 3.1.2 to 3.3.0, animations using the Lottie library are not working.
It works in developer mode, but not when built.
How can I solve this problem?

We get the data registered in microCMS with api/detail, get the json data with get communication based on the URL we got, and pass it to the Lottie component with props.

Package and version used:
vue3-lottie: ^2.5.0
axios: ^1.3.4

pages/detail.vue
```
<script setup lang="ts">
import axios from 'axios'
definePageMeta({
  layout: 'page',
})

const { data: detail, error }: any = await useFetch(`/api/detail`, {
  params: { slug: 'test' },
});
const detail = detail._value


let defaultOptions = { animationData: '' }
if(detail.subject.isTitleAnimation) {
  const { data: _animationData } = await axios.get(detail.subject.animationData.url)
  defaultOptions = {animationData: _animationData}
}


const animation = ref(null)
const handleAnimation = (anim: any) => {
  animation.value = anim
  anim.goToAndPlay(0.,true)
}

</script>
<template>
  <div>
    <template v-if="detail.subject.isTitleAnimation">
      <LazyLottie :options="defaultOptions" :project="true" @animCreated="handleAnimation" />
    </template>
  </div>
</template>
```

components/Lottie.vue
```
<script setup lang="ts">
import 'vue3-lottie/dist/style.css'
interface Props {
  options: any
}
const Props = defineProps<Props>()
interface Emits {
  (e: "animCreated", value: any): void
}
const emit = defineEmits<Emits>()
const animationSource = Props.options.animationData

const lavContainer = ref()
const onAnimLoad =() => {
  emit('animCreated', lavContainer.value)
}
</script>
<template>
  <span>
    <client-only>
      <Vue3Lottie
      renderer="svg"
      :loop="0"
      :animationData="animationSource"
      :rendererSettings="Props.options.rendererSettings"
      :style="{display: 'inline-block'}"
      ref="lavContainer"
      :pauseAnimation="true"
      @onAnimationLoaded="onAnimLoad"
      />
    </client-only>
  </span>
</template>
```

**Comment by megasanjay** [comment]
Is this an issue if you provide the lottie json directly in the component? There is also an [`animationLink`](https://vue3-lottie.vercel.app/guide.html#animationlink) prop that you can use if you want to use URLs.

**Comment by boeltazawa** [comment]
There is another page where I provided the json file directly, but this one works.
Also, after posting this issue, I tried using the animationLink property to specify the URL of the animation data, but this did not improve things.
If I output the animationSource value using console.log at the timing of the onAnimationLoaded event, I seem to be able to get the json file and URL value.

**Comment by megasanjay** [comment]
I think there might be a desync here. Would you mind creating a minimal reproduction so I can test this?

**Comment by boeltazawa** [comment]
OK, I'll make a duplicate.
Please wait a moment.

**Comment by boeltazawa** [comment]
Reproductions were made in the following repositories.
https://github.com/boeltazawa/nuxt3-lottie-test/tree/main

The URL deployed to Vercel is here.
https://nuxt3-lottie-test.vercel.app/

**Comment by boeltazawa** [comment]
Have you had a chance to look at the duplicates?
If you have any clues that might help me, I would appreciate it if you could let me know.

**Comment by megasanjay** [comment]
Hi @boeltazawa I forked the repo but I seem to need to connect to a CMS? Can I update that section to skip that?

**Comment by boeltazawa** [comment]
We have a commit that directly returns values that can be obtained from CMS when hitting api/detail, and will send it to you.
https://github.com/boeltazawa/nuxt3-lottie-test/tree/5f62fa167dcb8afaf6c1494726fa3a2ee2c639b9

I will also send you the URL of the deployed version of this commit to Vercel.
The lottie animation works here.

https://nuxt3-lottie-test-l5wqcxfyx-boel.vercel.app/

**Comment by megasanjay** [comment]
I'm still having issues with trying to run the application. Could you deploy your code on [Stackblitz](https://stackblitz.com/)? It should allow us to see the same dev environment.

**Comment by boeltazawa** [comment]
Sorry for the wait.
We have deployed the code to StackBlitz.
Please check it out.
https://stackblitz.com/edit/nuxt-starter-5f4ll9

When deploying to vercel, we do static generation.
If static generation is the cause of the problem, please let us know a good way to fix it, as we are considering another method.

**Comment by megasanjay** [comment]
I think pulling the data from the CMS is the issue. Also the stackblitz link is still not functional.
