### ISSUE TITLE
Import error in vue 3

### ISSUE THREAD

**Issue by Sukaato** [megasanjay/vue3-lottie#335]
**Describe the bug**
No typescript module found.

**To Reproduce**
1. Create a new vue project with Vite (vue + ts)
2. Install `vue3-lottie`
3. Add `import Vue3Lottie from 'vue3-lottie';` in main.ts

**Expected behavior**
No error

**Screenshots**
![image](https://github.com/megasanjay/vue3-lottie/assets/44368476/b3dc752f-40e2-412e-b2fb-48f4a1cb7ffb)

**Additional context**
dependencies
```
    "@vueuse/core": "^10.1.2",
    "lucide-vue-next": "^0.233.0",
    "vue": "^3.2.47",
    "vue-i18n": "^9.2.2",
    "vue-router": "^4.2.2",
    "vue3-lottie": "^2.7.1"
```
devDependencies
```
    "@tailwindcss/typography": "^0.5.9",
    "@types/node": "^18.16.18",
    "@typescript-eslint/eslint-plugin": "^5.59.11",
    "@typescript-eslint/parser": "^5.59.11",
    "@vitejs/plugin-vue": "^4.2.3",
    "@vue/eslint-config-typescript": "^11.0.3",
    "audit-ci": "^6.6.1",
    "autoprefixer": "^10.4.14",
    "daisyui": "^3.1.1",
    "eslint": "^8.43.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.14.1",
    "postcss": "^8.4.24",
    "prettier": "^2.8.8",
    "sass": "^1.63.4",
    "tailwind-scrollbar": "^3.0.4",
    "tailwindcss": "^3.3.2",
    "typescript": "^5.1.3",
    "vite": "^4.3.9",
    "vue-eslint-parser": "^9.3.1",
    "vue-tsc": "^1.8.0"
```

**Comment by Sukaato** [comment]
Error also prevents applications from being deployed.

![image](https://github.com/megasanjay/vue3-lottie/assets/44368476/571a717d-05d3-4f0b-a738-e3d264b11684)

**Comment by megasanjay** [comment]
Hi @Sukaato. Thank you for reporting the issue. I just released a [new version ](https://www.npmjs.com/package/vue3-lottie/v/2.7.3)of the library that should fix your issue. 

You can use `yarn add vue3-lottie@latest` or `npm install vue3-lottie@latest --save` to fix the issue in your Vue 3 app.

**Comment by yashwp** [comment]
I've install latest version of this package, but still getting:

Error: Cannot find module vue3-lottie or its corresponding type declarations.

In my Webstorm
