### ISSUE TITLE
Play / Pause Methods do not work

### ISSUE THREAD

**Issue by schmeiger** [megasanjay/vue3-lottie#35]
I've tried play and pause methods in my projects and it was not working... I thought I did something wrong, but in examples the car example is also not responding to any click events... Would be nice to have a fix for it :3 
https://vue3-lottie.vercel.app/examples.html#play-on-hover

**Comment by megasanjay** [comment]
For your case would you mind sharing an example? 

The reason the docs one doesn't work is a quirk of vitepress. Since I load the element after hydration it can sometimes bug out. If you look at the bottom of the page you should see all the elements.

**Comment by megasanjay** [comment]
Hi @schmeiger 

There was indeed a bug introduced by a recent PR that only affected the `pauseAnimation` prop. It has been fixed in v2.2.3. Please give that a try :)

**Comment by schmeiger** [comment]
Oh that was fast :)

I will give it a go! And will report ;)

**Comment by schmeiger** [comment]
ok... I've updated to "vue3-lottie": "^2.2.3" ...  but sadly it didn't fix it... The strange thing is that `autoplay: false` as prop is also ignored...

**Comment by megasanjay** [comment]
I will take a second look at it tonight. Its 4am currently lol

**Comment by megasanjay** [comment]
@schmeiger I pushed a fix for the `autoPlay` prop. That should work as intended now. However, I think you might need to use a different method for the animation for your use case. 

In this instance you should provide a `ref` to your lottie and run the methods manually. You can use `v-show` to hide the lottie above your heart button. 

When the button is clicked you can show the element to reveal the animation. At the same time you can call the [stop](https://vue3-lottie.vercel.app/guide.html#stop) and then the [play](https://vue3-lottie.vercel.app/guide.html#play) method. This should reset to the first frame and then play from there. To hide the animation after it is finished playing you can use the [onLoopComplete](https://vue3-lottie.vercel.app/guide.html#onloopcomplete) event to hide the animation again. 

Another alternative to the methods is to use the [pauseAnimation](https://vue3-lottie.vercel.app/guide.html#pauseanimation) prop to pause the animation onLoopComplete but you would have to time these correctly. 

A third alternative is to use the [goToAndPlay](https://vue3-lottie.vercel.app/guide.html#gotoandplay) method and then hide the animation onLoopComplete. 

Please let me know if this makes sense and if you need any more help. Thank you for using this library. Good luck :)

**Comment by schmeiger** [comment]
Cooooool! Autoplay did fix my 
`this.$refs.heartsLottie.play();`

I guess, I was confused that, when it was on autoplay and the animation ran to the end, it doesn't replay automatically :)
Now I know, that I just have to reset the timeline! :)
Thank you so much! :)

And thank you for your work in general, I was after a proper Lottie player in Vue 3 for a long time... now I found it! 🥰👏

**Comment by megasanjay** [comment]
@schmeiger Not sure if this was the case in your instance but you have `loop` set to 1 in your example. That would be most likely the reason why the animation ends even with `autoPlay` enabled.

**Comment by megasanjay** [comment]
@schmeiger The `loop` prop if provided a number might not be working as you expected. I think for your use case you could try listening to [onComplete](https://vue3-lottie.vercel.app/guide.html#oncomplete) instead? The `lottie-web` library I use internally might not be emitting the events for the first loop complete.

As for the `loop` prop itself, you can think of it as the number of repetitions instead: 
-  `true` is to loop forever.
- `false` is to not loop. (one plays once)
- `0` is to loop forever
- `1` is to loop once (this might not emit the `onLoopComplete` event)
- `x` where x > 1 is the number of times the animation should play from the loading time.

**Comment by schmeiger** [comment]
Oh, cool! :) Now I got, why my :loop="0" was looping forever, I thought, something was broken... :) 

That was basically my expectation -> if I set to autoPlay="true" and loop="0", the expected result -> it will play once and that's it, basically same as :loop=false :) 

 I think the info, that :loop=0 == loop forever, would be really useful in Docs :)
 Thank you so much for your time! 🥰 My Fav/Hearts Button is very buuuuuuutiful now!!! :D
